---
# These are Play level variables , because we kept the variable at top of playbook
- name: "Play level variables"
  hosts: local
  connection: local  # here local means ansible is connecting to localhost , it means where ansible is installed 
                      # there only , not to any other servers
  vars:               # vars is the syntax of variables within that we can declare and initilise the variables
    COURSE_NAME: "Ansible"
    TRAINER_NAME: "Siva"
  vars_files:
    - details.yaml
  tasks:
  - name: "Printing the variables"
    ansible.builtin.debug:    # debug is like echo , it prints the msg 
      msg: "Course name is :{{ COURSE_NAME }} and the trainer is {{ TRAINER_NAME }}"    

  # Task level variables
  - name: "Task level variables"
    vars:
      NAME: "DevOps Phani"
      ROLE: "DevOps Engineer"
    ansible.builtin.debug:
      msg: "Printing task level variables ::-> My name is {{ NAME }} and i am working as {{ ROLE }}"

  
  # Getting variables from other files
  - name: "Accessing variables from other files"
    ansible.builtin.debug:
      msg: "Accessing variables from other files ::-> My name is {{ NAME }} and my role is {{ DESIGNATION }}"

  

